[profile.release]
lto = true

[workspace]
resolver = "2"
members = [
    "protohackers",
    "smoke-test",
    "prime-time",
    "means-to-an-end",
    "budget-chat",
    "unusual-database-program",
    "mob-in-the-middle",
]
